[package]
name = "scratch_final"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
egui = "0.21.0"
image = "0.24.6"
rand = "0.8.5"
strum = "0.24.1"
strum_macros = "0.24.3"
